name: Students RFID Manager Builder

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-18.04, macos-latest, windows-latest, ubuntu-20.04]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build with pyinstaller
        run: |
          pyinstaller --name students-rfid-manager -w -F src/main.py